= Asciidoctor.js thesis template

I recently wrote my bachelors thesis in asciidoc. The biggest reason for doing so was that I wanted to use a typesetting system that I can actually understand. Asciidoc is also far easier to read than documents written in the common typesetting system for scientific writing.

.Benefits:
* Flexible; If you can design it in a browser you can also do it here
* Website and PDF; Your PDF can also be viewed as a website
* Easily readable source document; Basically markdown.


== Getting started

If you just want to start writing, you can go ahead and start in `paper.adoc`. To get a pdf use `make pdf`, to preview the pdf in a browser use `make preview`. You can also generate a website using `make index.html`. You need to have asciidoctor-web-pdf and make and some other things. The easiest way to get them on Linux or Mac is by using the nix package manager and type `nix develop` in the root of this repo.

I recommend using vscode for editing, as it has a good extension for live previewing.

=== Setup

After cloning this repo you can use `nix develop` to enter a shell with all neccessary tools. You should use vscode as your editor, as that has really good support for asciidoc and the settings are preconfigured in this repo. After you open this project in vscode, some extensions will be suggested to you. Install them. They add support for live preview and asciidoc syntax highlighting.

.Install deps without nix
[%collapsible]
====
If you dont use the nix package manager I recommend installing it. That way you are guaranteed to have the same versions of things that were used to create the template. Alternativly you can also install the dependencies manually. You need the following things:

* asciidoctor-js
* asciidoctor-web-pdf
* asciidoctor-kroki
* sass
* jq
* gnumake
* python3 (optional)
====

=== Toolchain

This template is completly based on web technologies, so modifying the template is as easy as modifying any other HTML/CSS website. This is a big 

=== Custom scripts

To add the features that are missing in asciidoc this template uses javascript in `<script>` tags. The javascript gets executed when the PDF is rendered. For the web version it is executed in the browser. I recommend using the snippets feature of chrome for for developing or modifying the scripts (devtool>sources>snippets). Dont be afraid to modify, delete or create new scripts, they are already quite hacky. 

All scripts are bundled in the `scripts/trailing-scripts.adoc` file which is inserted at the end of the document.

Most of the scripts are quite short and just do one thing like linking glossary entries to the glossary.

The scripts in trailing-scripts are executed while the browser is parsing the document. If you want to execute script a bit later or earlier, you can wait for the event that indicates when the browser is done. You can also execute scripts directly before and after pagedjs. See `scripts/included/fixPagebreaksInListings.adoc` for an example.

=== Source code lisitings

This template uses highlight.js for syntax highlighting code blocks in different languages. It brings a custom stylesheet, so the style of the text matches the rest of the paper.

To be able to use a custom stylesheet with highlightjs we need to include highlightjs with the template. The included version supports syntax highlighting for most common languages, but not all. If you need more, go to https://highlightjs.org/download/[the highlightjs download page], check the languages you need and download the file. Then you replace *only* `highlightjs/highlight.min.js` with the `highlight.min.js` from the downloaded archive.

This is basically the same as described in the https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/highlightjs/#use-a-custom-highlight-js-library[asciidoctor documentation].

PagedJS has a lot of trouble with breaking source listings over multiple pages. To mitigate this issue, this template includes a script that adjusts the `<code>` tags generated by asciidoctor. If you want to learn more about this problem read the comment in `scripts/included/fixPagebreaksInListings.adoc`.

=== Directory structure

The main file for your writings lives in the root of the repo and is called `paper.adoc`. All of the content execept for big charts or listings goes here. There are subdirectories for some things. I recommend putting your file only in the root dir or one directory deeper. The second-level subdirectories (`scripts/included`, `styles/default`) are mostly used for included scripts and stylesheets. You can modify the files in there, but you should not add new files, because you will lose track of which files are specific to your document and which are not. At least I do.

CAUTION: You can modify files in second-level subdirectories  (`scripts/included`, `styles/default`, ...), but *you should not add new files there*. You will lose track of which files are specific to your document and which are not. At least I do.

The `scripts` directory contains all the scripts that are used to build the document. Your scripts should go directly into the `scripts` directory, or in the trailing scripts file. Some scripts included with the template are store in the `included` directory. I dont recommend creating additional directories there, the included scripts are just there so they dont clutter your scripts in the scripts directory.

The `styles` directory contains the CSS files that are used to style the document. `paper.scss` is the main file, that imports all other scripts. It will be compiled with sass during the make process into a single big scss file. If you want to add some classes just put them directly in that file. `default` contains basic styles for everything, print these that are specific to print. If you modify them, you should consider contributing your changes back to the template repo.

The `assets` directory contains everything else that is content of your document, but too long for the main document. Probably just images, figures and long code listings. Short figures and code listings (less than 10 lines) should probably be in your main document.

The `libraries` directory contains things that are included in the template and required at runtime (except styles and scripts). For now it just contains highlightjs, but other libraries might also be placed here. vega-lite is currently loaded from a CDN but if it were included it would also go here. Maybe this should just be `assets/included`, but I am not sure about that yet.

== Philosophical questions

I want to explain a few of the decisions I made for this template.

Most graphical design decisions were inspired by the https://github.com/mbredel/thesis-template[latex thesis template of my university] which is seems to be based on https://ctan.org/pkg/classicthesis?lang=en[classicthesis]. If you are creating a thesis for h_da this template should fulfill all stylistic requirements.

This template also puts all content into a single file. I strongly believe that this makes working with large documents easier. Asciidoc also suits itself particularily well for this because it has nearly no boilerplate. I recommend using sticky scroll and word wrap, they should already be configured by the vscode workspace settings. Side-by-side view can also be useful, if you are working on two parts simultaneously. A mouse with forward and back buttons is also really useful.

I already explicitly decided against using bibtex for citations because that makes the whole setup less usable. I pratice I found the default asciidoctor glossary to works really well. Comments for each entry can be added as comments and links to the papers can just be included in the text. This is one of the decisions that worked out really well.


== Content

This section is aimed at giving practical examples of how you can do things that are commonly done in scientific writing. For most of them you should be able to find examples in paper.adoc, but I will try to go into more detail here. I will go through my thesis from the start to finish and will explain all the things that are unusual. You should be familiar with asciidoc syntax in general, I recommend skimming the first few chapters of documentation <https://docs.asciidoctor.org/asciidoc/latest/>

=== Settings

The document starts with a few attribute definitions. This is the biggest block of boilerplate/config.

=== Title page

The settings in the previous sections disabled a titlepage generated by asciidoctor, so we have to style it manually. In the template I just defined a few CSS classes (`university`, `faculty`, `presented-by`, ...) and applied them to the elements. Then I opened the document in preview mode and fiddled with the CSS until everything was arranged to my liking. I then copied my CSS to the paper.css stylesheet in the styles directory.

After the titlepage a `<<<` is inserted to force a new page

The title is also marked as `discrete` which means that it is ommitted from the table of contents.

=== Declaration

If you are writing a thesis you probably need this bit to confirm that you wrote it all by yourself. This template adds the `signature-required` CSS class which add a nice line where you can write your name.

=== Abstract

The abstract is just a normal section with the exception of it being marked as `discrete` so it doesn't show up in the table of contents.

=== Table of contents, figures, tables, listings

`toc::[]` gets replaced with the table of contents by asciidoctor.

This template includes a script to generate indices for figures, tables, listings. By default it is enabled, to deactivate it, uncomment it in scripts/trailing-scripts.adoc .

=== Numbering sections, figures, tables and listings

Asciidoctor can number sections, figures, tables and listings automatically. This template uses that feature.


=== Bibliography

